name: Pa11y CI Accessibility Tests
on:
  #schedule:
  #  - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - main

jobs:
  accessibility-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
          
      # Install Chrome and Puppeteer dependencies
      # Set Puppeteer environment variables
      #- name: Set Puppeteer env
       # run: |
         # echo "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true" >> $GITHUB_ENV
         # echo "PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium" >> $GITHUB_ENV

      # Cache pa11y dependencies
      - name: Cache Pa11y dependencies
        uses: actions/cache@v3
        with:
          path: ./pa11y/node_modules
          key: ${{ runner.os }}-pa11y-${{ hashFiles('./pa11y/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-pa11y-

      # Cache Vue app dependencies
      - name: Cache Vue app dependencies
        uses: actions/cache@v3
        with:
          path: ./app/node_modules
          key: ${{ runner.os }}-vue-${{ hashFiles('./app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-vue-

      # Run Pa11y tests
      - name: Install and run Pa11y
        working-directory: ./pa11y
        run: |
          npm ci
          DEBUG=pa11y* npm run test
          
       # Copy Pa11y report to app's public directory
      - name: Copy Pa11y report
        run: |
          cp ./pa11y/report.json ./app/dist/reports/

      # Build Vue app
      - name: Install and build Vue app
        working-directory: ./app
        run: |
          npm ci
          npm run build
          
     
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/dist
          publish_branch: gh-pages
          keep_files: false